name: Production Deploy

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: send notifictaion 
      run: | 
        echo ${{ github.run_id }} ;
        echo ${{ github.ref_name }};
        echo ${{ github.actor }} ;
        echo ${{ github.action_status	 }};
        # curl -X POST https://api.kakaowork.com/v1/messages.send \
        # -H "Authorization: Bearer ${{ secrets.APP_KEY }}" \
        # -H "Content-Type: application/json" \
        # -d '{"conversation_id": ${{ secrets.CONVENTION_ID }},"text":"카카오워크에 오신걸 환영합니다.",
        #     "blocks":[{"type":"text","text":"카카오워크에 오신걸 환영합니다.",
        #     "inlines":[{"type":"styled","text":"카카오워크에 "},
        #               {"type":"styled","text":"오신걸 ","bold":true},
        #               {"type":"styled","text":" 환영합니다.","color":"red"}]}]}' > /dev/null
